font:
  normal:
    family: Hack Nerd Font
    style: Bold 
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic

  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic

  size: 12

window:
  decorations: buttonless

padding:
  x: 10
  y: 10
